source 'https://rubygems.org'

# Declare your gem's dependencies in scorm_system.gemspec.
# Bundler will treat runtime dependencies like base dependencies, and
# development dependencies will be added by default to the :development group.
gemspec

# Declare any dependencies that are still in development here instead of in
# your gemspec. These might include edge Rails or gems from your path or
# Git. Remember to move these dependencies to your gemspec before releasing
# your gem to rubygems.org.

# To use a debugger
# gem 'byebug', group: [:development, :test]
#TODO Find the way to make this gem only in the gemspec work, when impoting from git
gem "scorm", :git => 'git://github.com/abenitoc/scorm.git', :branch => "master"
gem 'free_learn_core', path: '../core'
